src/java/com/admin/model/Afiliacion.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.admin.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author USER
 */
@Entity
@Table(name = "afiliacion")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Afiliacion.findAll", query = "SELECT a FROM Afiliacion a")
    , @NamedQuery(name = "Afiliacion.findById", query = "SELECT a FROM Afiliacion a WHERE a.id = :id")})
public class Afiliacion implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Column(name = "id")
    private Integer id;
    @JoinColumn(name = "conductor", referencedColumnName = "numeroid")
    @ManyToOne
    private Conductores conductor;
    @JoinColumn(name = "empresa", referencedColumnName = "numeroid")
    @ManyToOne
    private Empresa empresa;
    @JoinColumn(name = "vehiculo", referencedColumnName = "placa")
    @ManyToOne
    private Vehiculo vehiculo;

    public Afiliacion() {
    }

    public Afiliacion(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Conductores getConductor() {
        return conductor;
    }

    public void setConductor(Conductores conductor) {
        this.conductor = conductor;
    }

    public Empresa getEmpresa() {
        return empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    public Vehiculo getVehiculo() {
        return vehiculo;
    }

    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Afiliacion)) {
            return false;
        }
        Afiliacion other = (Afiliacion) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.admin.model.Afiliacion[ id=" + id + " ]";
    }
    
}

src/java/com/admin/controladores/AfiliacionController.java
package com.admin.controladores;

import com.admin.model.Afiliacion;
import com.admin.controladores.util.JsfUtil;
import com.admin.controladores.util.JsfUtil.PersistAction;
import com.admin.sessionBean.AfiliacionFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("afiliacionController")
@SessionScoped
public class AfiliacionController implements Serializable {

    @EJB
    private com.admin.sessionBean.AfiliacionFacade ejbFacade;
    private List<Afiliacion> items = null;
    private Afiliacion selected;

    public AfiliacionController() {
    }

    public Afiliacion getSelected() {
        return selected;
    }

    public void setSelected(Afiliacion selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private AfiliacionFacade getFacade() {
        return ejbFacade;
    }

    public Afiliacion prepareCreate() {
        selected = new Afiliacion();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("AfiliacionCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("AfiliacionUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("AfiliacionDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Afiliacion> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Afiliacion getAfiliacion(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Afiliacion> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Afiliacion> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Afiliacion.class)
    public static class AfiliacionControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            AfiliacionController controller = (AfiliacionController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "afiliacionController");
            return controller.getAfiliacion(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Afiliacion) {
                Afiliacion o = (Afiliacion) object;
                return getStringKey(o.getId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Afiliacion.class.getName()});
                return null;
            }
        }

    }

}

web/afiliacion/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="AfiliacionCreateDlg" widgetVar="AfiliacionCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateAfiliacionTitle}">
            <h:form id="AfiliacionCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{afiliacionController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateAfiliacionLabel_id}" for="id" />
                        <p:inputText id="id" value="#{afiliacionController.selected.id}" title="#{bundle.CreateAfiliacionTitle_id}" required="true" requiredMessage="#{bundle.CreateAfiliacionRequiredMessage_id}"/>
                        <p:outputLabel value="#{bundle.CreateAfiliacionLabel_conductor}" for="conductor" />
                        <p:selectOneMenu id="conductor" value="#{afiliacionController.selected.conductor}" >
                            <f:selectItems value="#{conductoresController.itemsAvailableSelectOne}"
                                           var="conductorItem"
                                           itemValue="#{conductorItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateAfiliacionLabel_empresa}" for="empresa" />
                        <p:selectOneMenu id="empresa" value="#{afiliacionController.selected.empresa}" >
                            <f:selectItems value="#{empresaController.itemsAvailableSelectOne}"
                                           var="empresaItem"
                                           itemValue="#{empresaItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateAfiliacionLabel_vehiculo}" for="vehiculo" />
                        <p:selectOneMenu id="vehiculo" value="#{afiliacionController.selected.vehiculo}" >
                            <f:selectItems value="#{vehiculoController.itemsAvailableSelectOne}"
                                           var="vehiculoItem"
                                           itemValue="#{vehiculoItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{afiliacionController.create}" value="#{bundle.Save}" update="display,:AfiliacionListForm:datalist,:growl" oncomplete="handleSubmit(args,'AfiliacionCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="AfiliacionCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/afiliacion/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="AfiliacionEditDlg" widgetVar="AfiliacionEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditAfiliacionTitle}">
            <h:form id="AfiliacionEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{afiliacionController.selected != null}">
                        <p:outputLabel value="#{bundle.EditAfiliacionLabel_id}" for="id" />
                        <p:inputText id="id" value="#{afiliacionController.selected.id}" title="#{bundle.EditAfiliacionTitle_id}" required="true" requiredMessage="#{bundle.EditAfiliacionRequiredMessage_id}"/>
                        <p:outputLabel value="#{bundle.EditAfiliacionLabel_conductor}" for="conductor" />
                        <p:selectOneMenu id="conductor" value="#{afiliacionController.selected.conductor}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{conductoresController.itemsAvailableSelectOne}"
                                           var="conductorItem"
                                           itemValue="#{conductorItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditAfiliacionLabel_empresa}" for="empresa" />
                        <p:selectOneMenu id="empresa" value="#{afiliacionController.selected.empresa}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{empresaController.itemsAvailableSelectOne}"
                                           var="empresaItem"
                                           itemValue="#{empresaItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditAfiliacionLabel_vehiculo}" for="vehiculo" />
                        <p:selectOneMenu id="vehiculo" value="#{afiliacionController.selected.vehiculo}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{vehiculoController.itemsAvailableSelectOne}"
                                           var="vehiculoItem"
                                           itemValue="#{vehiculoItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{afiliacionController.update}" value="#{bundle.Save}" update="display,:AfiliacionListForm:datalist,:growl" oncomplete="handleSubmit(args, 'AfiliacionEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="AfiliacionEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/afiliacion/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListAfiliacionTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="AfiliacionListForm">
                <p:panel header="#{bundle.ListAfiliacionTitle}">
                    <p:dataTable id="datalist" value="#{afiliacionController.items}" var="item"
                                 selectionMode="single" selection="#{afiliacionController.selected}"
                                 paginator="true"
                                 rowKey="#{item.id}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAfiliacionTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAfiliacionTitle_conductor}"/>
                            </f:facet>
                            <h:outputText value="#{item.conductor}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAfiliacionTitle_empresa}"/>
                            </f:facet>
                            <h:outputText value="#{item.empresa}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAfiliacionTitle_vehiculo}"/>
                            </f:facet>
                            <h:outputText value="#{item.vehiculo}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{afiliacionController.prepareCreate}" update=":AfiliacionCreateForm" oncomplete="PF('AfiliacionCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":AfiliacionViewForm" oncomplete="PF('AfiliacionViewDialog').show()" disabled="#{empty afiliacionController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":AfiliacionEditForm" oncomplete="PF('AfiliacionEditDialog').show()" disabled="#{empty afiliacionController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{afiliacionController.destroy}" update=":growl,datalist" disabled="#{empty afiliacionController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/afiliacion/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="AfiliacionViewDlg" widgetVar="AfiliacionViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewAfiliacionTitle}">
            <h:form id="AfiliacionViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{afiliacionController.selected != null}">
                        <h:outputText value="#{bundle.ViewAfiliacionLabel_id}"/>
                        <h:outputText value="#{afiliacionController.selected.id}" title="#{bundle.ViewAfiliacionTitle_id}"/>
                        <h:outputText value="#{bundle.ViewAfiliacionLabel_conductor}"/>
                        <h:outputText value="#{afiliacionController.selected.conductor}" title="#{bundle.ViewAfiliacionTitle_conductor}"/>
                        <h:outputText value="#{bundle.ViewAfiliacionLabel_empresa}"/>
                        <h:outputText value="#{afiliacionController.selected.empresa}" title="#{bundle.ViewAfiliacionTitle_empresa}"/>
                        <h:outputText value="#{bundle.ViewAfiliacionLabel_vehiculo}"/>
                        <h:outputText value="#{afiliacionController.selected.vehiculo}" title="#{bundle.ViewAfiliacionTitle_vehiculo}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="AfiliacionViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>